[tox]
envlist = py310,py311,py312
package = wheel

[testenv]
changedir = {envdir}
extras =
    dev
commands_pre =
    cp -r {toxinidir}/releasenotes {envdir}
    cp {toxinidir}/.bogrod {envdir}
commands =
    pytest --pyargs bogrod
allowlist_externals =
    pytest 
    cp
