name: sbom checks using bogrod

# ****
# **** This is for demo purpose only -- does not actually check the bogrod sbom
# ****

on:
  push:
    branches:
      - "release/demo**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install sbom tools
      run: |
        make install-sbom-tools
    - name: check sbom
      run: |
        make sbom
